AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Spring Boot 3 API

Globals:
  Function:
    Timeout: 30
    MemorySize: 2048

Resources:
  SpringBootFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.example.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: target/aws-sdk-1.0-SNAPSHOT.jar
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
