# Reduce logging level to make sure the application works with SAM local
# https://github.com/aws/serverless-java-container/issues/134
logging.level.root=WARN
logging.level.root=INFO
logging.level.org.example=INFO

# Speed up startup: initialize beans only when first needed
spring.main.lazy-initialization=true

# Skip unnecessary checks on startup
spring.jmx.enabled=false
spring.main.banner-mode=off

# AWS Credentials
aws.accessKeyId=YOUR_ACCESS_KEY_ID
aws.secretAccessKey=YOUR_SECRET_ACCESS_KEY
aws.region=eu-central-1

# SQS
aws.sqs.queue-url=https://sqs.eu-central-1.amazonaws.com/864456252731/awssdksqs

# SES
aws.ses.sender-email=your-verified-sender@example.com
aws.ses.recipient-email=your-recipient@example.com

# Hot reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.poll-interval=1s
spring.devtools.restart.quiet-period=400ms